name: GitHub Actions Build
run-name: Build java application then create docker image
on: [push]
env:
  IMAGE_NAME: call-sign-telegram-bot
  GCP_PROJECT_ID: transceivers-collection
  GCP_REPOSITORY: k2callsign-images
  GCP_REGION: europe-central2
  GCP_LOCATION: europe-central2-docker.pkg.dev/transceivers-collection/k2callsign-images/call-sign-telegram-bot
jobs:
  Build-Java-Application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
      - name: Build Java Application
        run: mvn -B package -DskipTests
      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }} .
      - name: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Use gcloud CLI
        run: gcloud info
      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet
      - name: Show images
        run: docker images
      - name: Tag image
        run: docker tag ${{ env.IMAGE_NAME }} ${{ env.GCP_LOCATION }}
      - name: Push image
        run: docker push ${{ env.GCP_LOCATION }}
